# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.workers.max=1
org.gradle.vfs.watch=false
kotlin.daemon.jvm.options=-Xmx512m
kotlin.incremental=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Stripe Keys
STRIPE_PUBLISHABLE_KEY="pk_test_51TpTC7RwhaV5daLPo13r1viAMtXjdrCr67NS6KaZYQmjrTwqGW2LOxpRibwmabI0P11i77gNMXOs7zp9b3MoJ5xv00HY6He5CJ"
