# EMERGENCY OPTIMIZATION FOR 54 MODULES + LOW RAM
# Give Gradle 2GB total (max allowed usually for 4GB system)
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# ONLY configure modules that are actually needed for the task
org.gradle.configureondemand=true

# Force Gradle to be extremely patient and single-threaded
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=true
org.gradle.vfs.watch=false

# Keep Kotlin compiler outside the main Gradle process to give Dexing more room
kotlin.compiler.execution.strategy=daemon
kotlin.daemon.jvm.options=-Xmx512m
kotlin.incremental=true

android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Stripe Keys
STRIPE_PUBLISHABLE_KEY="pk_test_51TpTC7RwhaV5daLPo13r1viAMtXjdrCr67NS6KaZYQmjrTwqGW2LOxpRibwmabI0P11i77gNMXOs7zp9b3MoJ5xv00HY6He5CJ"
